# Generated by Django 5.1.5 on 2025-01-20 12:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "registration_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Inscrição"
                    ),
                ),
                (
                    "hidrometer_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número do Hidrômetro"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "Imóveis",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WaterBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_date", models.DateField(verbose_name="Data da Conta")),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                (
                    "consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Consumo (m³)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor (R$)",
                    ),
                ),
                (
                    "meter_reading",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Leitura do Hidrômetro",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("paid", "Pago"),
                            ("overdue", "Vencido"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bill_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bills/%Y/%m/",
                        verbose_name="Imagem da Conta",
                    ),
                ),
                (
                    "bill_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="bills/%Y/%m/",
                        verbose_name="PDF da Conta",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_bills",
                        to="bills.property",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta de Água",
                "verbose_name_plural": "Contas de Água",
                "ordering": ["-bill_date"],
            },
        ),
        migrations.CreateModel(
            name="Consumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "average_daily_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_history",
                        to="bills.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("property", "date")},
            },
        ),
    ]
